---
title: "A propos"
description: |
  Quelques détails et une précision historique
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Le groupe State Of The R Rennes est construit sur le modèle du groupe State Of The R Paris. Il regroupe des chercheurs, doctorants, enseignants,  ingénieurs, post-doctorants utilisateurs avertis de R avec l'objectif de maintenir une veille active autour des innovations de ce logiciel. 

Il dispose d'une liste de diffusion stateofther@listes.univ-rennes1.fr.

A ce jour la liste de ses membres 

Alglave Baptiste - ACO ESE
Cornillon Pierre-André - Rennes 2
Day Louise - ACO ESE
Lecomte Jean-Baptiste - Ifremer EMH
Emily Mathieu - ACO IRMAR
Etienne Marie-Pierre - ACO IRMAR
Giacofci Madison - Rennes 2
Guitton Jérôme - ACO ESE
Guibourd De Luzinais Vianney - ACO ESE
Hernvann Pierre-Yves - NOAA
Houée-Bigot Magalie - ACO IRMAR
Husson François - ACO IRMAR
Krell Nathalie - Rennes 1 
Lé Sébastien - ACO IRMAR
Marchand Jean-Louis - ACO IRMAR
Navaro Pierre - Rennes 1
Ougier Sandra - ACO ESE
Patin Rémi - ACO ESE
Rivot Etienne - ACO ESE
Rouvière laurent - Rennes 2
Swareh Ousmane - ACO IRMAR

